### ISSUE TITLE
liststucktasks command not found in v10.0.5.1

### ISSUE THREAD

**Issue by SESIKANTH** [ibm-apiconnect/apicops#11]
Dear team, 

apicops task-queue:list-stuck-tasks
 ›   Error: command task-queue:list-stuck-tasks not found

**Comment by WilliamMcEnery** [comment]
Hi @SESIKANTH,

`apicops task-queue:list-stuck-tasks` is only available for v2018, it is not needed for API Connect v10, you can use `apicops tasks:list` instead.

Thanks
