### ISSUE TITLE
Version v0.10.72 throws error

### ISSUE THREAD

**Issue by servicebroker** [ibm-apiconnect/apicops#13]
When using the latest version of apicops with out pipeline, we receive the following error when executing `apicops versions`

`Error relocating /usr/local/bin/apicops: fcntl64: symbol not found`

We did not have this issue with v.0.10.71

Are there any manual steps that need to be applied for migrating to this version?

**Comment by WilliamMcEnery** [comment]
@servicebroker There should be no extra manual steps, can you provide us with more information so we might be able to reproduce this issue.

**Comment by evanskinner** [comment]
@WilliamMcEnery I think this might be the same cause as https://github.com/ibm-apiconnect/apicops/issues/14 we should statically link apicops, but the latest version is dynamically linked

**Comment by WilliamMcEnery** [comment]
@servicebroker We have made some changes to apicops 0.10.72, can you please download it and try running it. Thanks.
