### ISSUE TITLE
Version v0.10.72 requires GLIBC 2.27

### ISSUE THREAD

**Issue by porteg** [ibm-apiconnect/apicops#14]
Hi.

I have seen that the latest versión (v0.10.72) fails in Linux because of you requires the GLIBC_2.27. I have used the v0.10.70 without any issue.

Is this a new requirement.

<img width="670" alt="image" src="https://github.com/user-attachments/assets/6737fd5e-60d0-4578-9995-64979a19a444">

Regards.

**Comment by evanskinner** [comment]
Thanks for the report @porteg. apicops should be statitcally linked, to avoid that kind of thing, but it looks like it is dynamically linked. We will fix that.

**Comment by WilliamMcEnery** [comment]
@porteg We have made changes to apicops 0.10.72, can you download it again and try running it, thanks.

**Comment by porteg** [comment]
Hi @WilliamMcEnery 

I have just tested it and it works fine.

Thanks for your help.
