### ISSUE TITLE
-n option is not working properly (macos)

### ISSUE THREAD

**Issue by danielcastellano** [ibm-apiconnect/apicops#5]
Hi!

Using the -n option, the apicops is not able to find the required pod:
`./apicops iss -n <client_namespace>`
`Current local date/time 6/25/2020, 3:16:45 PM [Current UTC time: 2020-06-25T13:16:45.629Z]
(node:5454) ExperimentalWarning: The fs.promises API is experimental`
`apicops 0.2.112`
`Did not find any running apim-v2 pods. Please check your KUBECONFIG env var is pointing to the correct cluster and/or Namespace is pointing to where the apim-v2 pods are.`

Changing the default namespace on the KUBECONFIG to the <client_namespace> one works, so it is clear that the apicops is using the KUBECONFING default namespace even if you used the -n option.

**Comment by chrisdudley** [comment]
I think that’s working as designed. The -n option is so you don’t have to provide the namespace in your kubeconfig. But if you do put it in your kubeconfig then that takes precedence.

**Comment by danielcastellano** [comment]
It's not working as designed, that's sure.
It seems that the kubeconfig default namespace is taking precedence, but it should. First because the -n option is more specific and second because all the documentation and the program help says that the -n option "will override any namespace you may have set in your kubeconfig"

```
> ./apicops iss --help
Current local date/time 6/30/2020, 9:29:59 AM [Current UTC time: 2020-06-30T07:29:59.149Z]
(iss) Identifies the state of any gateway and portal services and returns any associated task IDs that are incomplete. Can output compact or beautified and text or JSON

USAGE
  $ apicops services:identify-state

OPTIONS
  -a, --allWebhooks            Identify the state of gateway and portal services and display data for all identified webhook ids (-e -j -c have no effect when used with this)
  -e, --embellish              Output a table per service instead of single lines. In JSON mode beautify the JSON
  -j, --json                   Output as raw JSON instead of lines/tables
  -k, --kubeconfig=kubeconfig  The KUBECONFIG to use (this will override any KUBECONFIG environment variable you may have set)
  -n, --namespace=namespace    The kubernetes namespace to target (this will override any namespace you may have set in your kubeconfig)
  -w, --webhookId=webhookId    The id of the webhook subscription record for the service you want to display information about (-e -j -c have no effect when used with this)

ALIASES
  $ apicops iss

EXAMPLES
  $ apicops services:identify-state  # Identify the state of gateway and portal services
  $ apicops iss                    # Identify the state of gateway and portal services
  $ apicops iss -w <webhook id>     # Display data for provided webhook id
  $ apicops iss -a                  # Identify the state of gateway and portal services and display data for all identified webhook ids

```

In addition to the program output, the -n option is also commented on the README.md on this project.
I'm pretty sure that on previous apicops version, the -n worked correctly, but I don't remember which version.

**Comment by danielcastellano** [comment]
Fixed on the last version:
```
> ./apicops iss -n apiconnecteurobits2018
Current local date/time 7/8/2020, 7:12:14 PM [Current UTC time: 2020-07-08T17:12:14.024Z]
apicops 0.2.116
Apim Pod version is: 2018.4.1.10 ( apim:2018.4.1-1141-bd7c128 )
[...]
```
